name: Publicar na Hostgator
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.HOSTGATOR_FTP_SERVER }}
        ftp-username: ${{ secrets.HOSTGATOR_FTP_USER }}
        ftp-password: ${{ secrets.HOSTGATOR_FTP_PASS }}
